name: petperfect_exercise
description: assignment for pet perfect
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  hive: ^2.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
